### ISSUE TITLE
InnerHTML

### ISSUE THREAD

**Issue by nlvo** [MohamadAlGhorani/web-app-from-scratch-1920#10]
Zoals we het erover hadden, is innerHTML niet de beste practice. Maar ik zie dat je wel gebruik maakt van appendChild and createElement.
https://github.com/MohamadAlGhorani/web-app-from-scratch-1920/blob/bd71a30359ac0fc148eeab4c07070628c56ce35b/src/js/render.js#L29

**Comment by MohamadAlGhorani** [comment]
Ik heb het hier gebruikt omdat in de text die vanuit de data komt zit er al <br> in. en als ik textContent gebruik inplaats van innerHTML komt dan op de interface text met <br> tussen in.
Daarom heb ik het hier gebruikt verder als ik deze probleem wil oplossen moet ik dan de data opschonen en alle <br> elements vanuit de text halen.
