### ISSUE TITLE
You could do this more fancy and look smarter

### ISSUE THREAD

**Issue by kriskuiper** [MohamadAlGhorani/web-app-from-scratch-1920#11]
It's all okay like this though, but you could do something like:
```js
fetch(endpoint)
  .then(cleanData)
  .catch(console.log)
```

https://github.com/MohamadAlGhorani/web-app-from-scratch-1920/blob/bd71a30359ac0fc148eeab4c07070628c56ce35b/src/js/api.js#L9-L10

**Comment by MohamadAlGhorani** [comment]
klopt het zit fancyer en smarter eruit. Maar ik vind het zoals het is meer duidelijk voor me zelf en ik kan dan zien welke parameters geef ik mee aan de functies. Thanx 👍
