### ISSUE TITLE
Why not articles?

### ISSUE THREAD

**Issue by kriskuiper** [MohamadAlGhorani/web-app-from-scratch-1920#12]
I think allArticle sounds a bit weird but okay. If you do this consistent it's okay but yeah still a bit weird

https://github.com/MohamadAlGhorani/web-app-from-scratch-1920/blob/bd71a30359ac0fc148eeab4c07070628c56ce35b/src/js/render.js#L13

**Comment by MohamadAlGhorani** [comment]
I changed it 👍
