### ISSUE TITLE
You also render the data in cleanData

### ISSUE THREAD

**Issue by kriskuiper** [MohamadAlGhorani/web-app-from-scratch-1920#13]
🤔 I would just return the cleaned data here because you now get weird side effects. Also, this doesn't apply to your actor diagram etc.

https://github.com/MohamadAlGhorani/web-app-from-scratch-1920/blob/bd71a30359ac0fc148eeab4c07070628c56ce35b/src/js/data.js#L5-L11

**Comment by MohamadAlGhorani** [comment]
Done 👍
