### ISSUE TITLE
I think you should take a look at this

### ISSUE THREAD

**Issue by kriskuiper** [MohamadAlGhorani/web-app-from-scratch-1920#14]
Why are you changing the Array prototype?

I think you could do something like:

```js
Array.from(inputs).forEach(input => {
  input.addEventListener('change', (event) => {
    console.log(1)
  }
})
```

https://github.com/MohamadAlGhorani/web-app-from-scratch-1920/blob/bd71a30359ac0fc148eeab4c07070628c56ce35b/src/js/filter.js#L36-L39

**Comment by MohamadAlGhorani** [comment]
i changed the hole logic with you 👍  thanks
