### ISSUE TITLE
Assessment

### ISSUE THREAD

**Issue by kriskuiper** [MohamadAlGhorani/web-app-from-scratch-1920#15]
# 🍑 Assessment:

## App structure and code quality ⚠️
1. You could be more consistent here but it's okay and structured well. I also think you should do some research on when to use let and when to use const. Also the render function consists of a lot of code which does make it kinda unreadable.
2. Modules are somewhat the same as your diagrams say but not completely. As far as I can see you do your best not to use the global scope as much. Some functions got side effects which makes your code a bit hard to comprehend.

## Get and manipulate data ⚠️ 
3. You get data with fetch, clean and render it 👍cleaning pattern could be a bit more netjes 🥅 though.
4. Use of filter in cleanData, could add a comment since you told me it only removes one item.
5. You could use a template engine, I think that also would make your code a bit simpler because you lose all the ---child things.

## UX and diagrams ⚠️ 
6. Routing will be okay in the future since you're using routie
7. You could use some decision thingies in your interaction diagram and your actor diagram doesn't need arrows specifically
8. You could implement this in your filter like showing active filters and add loading states etc.

**Comment by MohamadAlGhorani** [comment]
Bedankt man 👍
