### ISSUE TITLE
Using ES5

### ISSUE THREAD

**Issue by nlvo** [MohamadAlGhorani/web-app-from-scratch-1920#2]
You're mixing ES5 and ES6.
https://github.com/MohamadAlGhorani/web-app-from-scratch-1920/blob/6a5e5d0f31b672e7284b643702a6aceef8a02fb1/src/js/renderData.js#L14

**Comment by nlvo** [comment]
For example https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Template_literals

**Comment by MohamadAlGhorani** [comment]
thanks i fixed it
