### ISSUE TITLE
Make installation guide more complete in README

### ISSUE THREAD

**Issue by titmousemees** [MohamadAlGhorani/web-app-from-scratch-1920#4]
- ~~If you dont have node js on your device download it first from here.~~
- Clone the project **[clone URL].**
- ~~Open the terminal and navigate to the project folder and run npm install to install the node modules.~~
- **type npm install in command line of root of folder**
- ~~Run in your terminal~~ **type** npm start ~~to open the project in your favorite browser~~  **in root of folder and navigate in browser to:** localhost:1234.

**Comment by MohamadAlGhorani** [comment]
Done 👍
