### ISSUE TITLE
Declare constants on the top/beginning of file

### ISSUE THREAD

**Issue by titmousemees** [MohamadAlGhorani/web-app-from-scratch-1920#6]
https://github.com/MohamadAlGhorani/web-app-from-scratch-1920/blob/6a5e5d0f31b672e7284b643702a6aceef8a02fb1/src/js/renderData.js#L7-L8

https://github.com/MohamadAlGhorani/web-app-from-scratch-1920/blob/6a5e5d0f31b672e7284b643702a6aceef8a02fb1/src/js/renderData.js#L10-L11

https://github.com/MohamadAlGhorani/web-app-from-scratch-1920/blob/6a5e5d0f31b672e7284b643702a6aceef8a02fb1/src/js/renderData.js#L13

https://github.com/MohamadAlGhorani/web-app-from-scratch-1920/blob/6a5e5d0f31b672e7284b643702a6aceef8a02fb1/src/js/renderData.js#L17

**Comment by MohamadAlGhorani** [comment]
thanks maar ik ga daar mee niks doen omdat ik geen global variabelen wil ik hebben :D
