### ISSUE TITLE
Interaction diagram onduidelijk

### ISSUE THREAD

**Issue by nlvo** [MohamadAlGhorani/web-app-from-scratch-1920#8]
Het gedeelte van de homepagina en de data ophalen is duidelijk, maar hoe de detailpagina wordt gerenderd is vanuit de router is onduidelijk. Het lijkt alsof er niks wordt gedaan met de api en data, maar je vertelde dat je een keer je data ophaalt en dat rendert.

**Comment by MohamadAlGhorani** [comment]
Ik heb het gefixt 👍
